// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task1PackagesSender.Data;

namespace Task1PackagesSender.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task1PackagesSender.Models.AcceptingPerson", b =>
                {
                    b.Property<int>("AcceptingPersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ACP_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnName("ACP_Category");

                    b.Property<decimal>("Limit")
                        .HasColumnName("ACP_Limit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("ACP_Login");

                    b.Property<decimal?>("SubstituteLimit")
                        .HasColumnName("ACP_SubstituteLimit");

                    b.Property<string>("SubstituteLogin")
                        .HasColumnName("ACP_SubstituteLogin");

                    b.HasKey("AcceptingPersonID");

                    b.ToTable("AcceptingPeople");
                });

            modelBuilder.Entity("Task1PackagesSender.Models.Employees", b =>
                {
                    b.Property<int>("EmoplyeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ORG_ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnName("ORG_Login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("ORG_Name");

                    b.Property<int?>("ORG_ManagerID");

                    b.HasKey("EmoplyeeID");

                    b.HasIndex("ORG_ManagerID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Task1PackagesSender.Models.Employees", b =>
                {
                    b.HasOne("Task1PackagesSender.Models.Employees", "employees")
                        .WithMany()
                        .HasForeignKey("ORG_ManagerID");
                });
#pragma warning restore 612, 618
        }
    }
}
